FROM mcr.microsoft.com/mssql/server:2019-latest
ENV ACCEPT_EULA=y
ENV SA_PASSWORD=Password123!
EXPOSE 1433
#RUN mkdir -p /usr/src/app
#WORKDIR /usr/src/app
#COPY . /usr/src/app
#RUN chmod +x /usr/src/app/run-initialization.sh
#CMD /bin/bash ./entrypoint.sh
