using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace webbot.Migrations
{
    public partial class SeedPlayers : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (1, 'Sg Mini', 'sg.mini@yandex.com', 'ouroboros', NULL, '102702940244381', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (2, 'Afraa Saad', 'saad_afraa@yahoo.com', 'castleage1234', NULL, '100004141329510', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (3, 'Agárdi Zoli', 'dsragardizoli@freemail.hu', 'qwertz1234@', 'qwertz1234@', '100000866850221', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (4, 'Alain Fuscet', 'gordonkey1@gmail.com', 'qwertz1234', 'qwertz321', '100004707390895', 'E44F7B', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (5, 'Alawi', 'alitaha7171@yahoo.com', '12341234@', NULL, '100009301367228', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (6, 'Alush', 'alisalamali66@yahoo.com', '12341234@', NULL, '100009411072497', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (7, 'Alexandra Halász', 'dsralexandra@freemail.hu', 'qwertz1234', 'qwertz1234@', '100005594558479', 'C276D2', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (8, 'Ali Hanash', 'hali.rablo@freemail.hu', '4l1h4n4sh', NULL, '1644963973', '289A73', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (9, 'ali2000sabri@yahoo.com', 'ali2000sabri@yahoo.com', 'castleage1234', NULL, '100005042735447', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (10, 'Anette Halász', 'dsranette@freemail.hu', 'qwertz1234', 'qwertz1234@', '100005719772670', '0E8DD5', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (11, 'Bassam', 'bassamsalam66@yahoo.com', '12341234@', NULL, '100009220555920', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (12, 'Bognár Mária (Cecill)', 'dsrcecill@freemail.hu', 'qwertz1234', 'qwertz1234@', '100002542879699', 'E697C9', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (13, 'Bridget Fuscet', 'bridget.fuscet@gmail.com', 'qwertz1234', 'qwertz321', '100004727670608', '235CF4', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (14, 'Dhaemo', 'dsrdhaemon@freemail.hu', 'qwertz1234', 'qwertz1234@', '100000861585571', 'F13E57', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (15, 'DSR', 'dsrhungary@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003116491071', '7F0CA7', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (16, 'Emad', 'emadtahaemad@yahoo.com', '12341234@', NULL, '100009271368597', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (17, 'Endre Fisher', 'dsrendre@freemail.hu', 'qwertz1234', 'qwertz1234@', '100006649718909', 'B397BC', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (18, 'Eros Pista', 'dsreros@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003116491071', '7F0CA7', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (19, 'Ezcsak Norrisz', 'dsrezcsak@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003179924458', '1542BB', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (20, 'Fehér Ork', 'dsrfeher@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003125597402', '59BB3D', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (21, 'Fogarasi Bálint ', 'dsrbalint@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003486814784', '4EA32D', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (22, 'Fogarasi Dávid', 'dav.fogarasi@gmail.com', 'qwertz1234', 'qwertz1234', '100006633580737', '847160', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (23, 'Fogarasi Máté', 'dsrmate@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003474546048', '87FFD0', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (24, 'Gabrielle Halász', 'dsrgabrielle@freemail.hu', 'qwertz1234', 'qwertz1234@', '100005777674520', 'C255ED', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (25, 'Half Ork', 'dsrhalfork@freemail.hu', 'qwertz1234', 'qwertz1234@', '100000629428548', '57B977', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (26, 'Half Elf', 'dsrhalfelf@freemail.hu', 'qwertz1234', 'qwertz1234@', '100000654778050', '03852A', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (27, 'hamodysabri2001@yahoo.com', 'hamodysabri2001@yahoo.com', 'castleage1234', NULL, '100005114853023', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (28, 'Hiba', 'hibasalamhiba@yahoo.com', '12341234@', NULL, '100009526327095', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (29, 'Hound Dark', 'dsrhound@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003130846744', '32626C', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (30, 'Jean Fuscet', 'jean.fuscet@gmail.com', 'qwertz1234', 'qwertz321', '100004741890668', '78403E', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (31, 'Kalid', 'kalidsalimkalid@yahoo.com', '12341234@', NULL, '100009605403255', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (32, 'Károly', 'dsrkaroly@freemail.hu', 'qwertz1234', 'qwertz1234@', '100000775105753', '7D394F', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (33, 'Katalin Fisher', 'katalinfisher@gmail.com', 'qwertz1234', 'qwertz1234', '100006746198508', '529C28', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (34, 'Kopján Kiss Gábor', 'dsrkkg@freemail.hu', 'qwertz1234', 'qwertz1234@', '1495170998', '1EDC02', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (35, 'Kugler Gábor', 'kuglergabor2015@gmail.com', '&rose1&', NULL, '1021117214', 'EA3BFA', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (36, 'Laith', 'laithsalamlaith@yahoo.com', '12341234@', NULL, '100009673560085', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (37, 'Lefi Bubu', 'dsrlefi@freemail.hu', 'qwertz1234', 'qwertz1234@', '100001598939094', 'D2207D', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (38, 'Lina', 'tlsr4@yahoo.com', 'castleage1234', NULL, '100003548812963', 'E4C745', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (39, 'Mahir', 'mahirsamimahir@yahoo.com', '12341234@', NULL, '100009638941432', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (40, 'Mazi', 'mazinsamimazin@yahoo.com', '12341234@', NULL, '100009568804309', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (41, 'Meriel', 'dsrmeriel@freemail.hu', 'qwertz1234', 'qwertz1234@', '100002029789761', '9F4966', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (42, 'Mészáros Péter', 'dsrpeter@freemail.hu', 'qwertz1234', 'qwertz1234@', '1478978473', 'B1278A', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (43, 'Mészáros Zoltá', 'dsrzoltan@freemail.hu', 'qwertz1234', 'qwertz1234@', '100002247786172', 'B83B80', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (44, 'Muhannad', 'muhannadsami67@yahoo.com', '12341234@', NULL, '100009545945307', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (45, 'Mustafa', 'mustafasami177@yahoo.com', '12341234@', NULL, '100009326926979', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (46, 'Natasha', 'dsrnatasha@freemail.hu', 'qwertz1234', 'qwertz1234@', '100005626026209', 'B4140F', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (47, 'Nixi Killerbee', 'nixi.cam@gmail.com', 'nokia98', NULL, '100000740695190', '2D63BE', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (48, 'Omar Taha', 'omar_farooq68@yahoo.com', 'castleage1234', 'qwertz1234@', '100004263670035', '7ADC44', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (49, 'Pöci', 'dsrpoci@freemail.hu', 'qwertz1234', 'qwertz1234@', '100000743009101', 'D227A2', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (50, 'Pecás', 'dsrpecas@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003594492945', 'AB54BE', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (51, 'Rula Thaer', 'rulathaer@yahoo.com', 'castleage1234', NULL, '100008261147627', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (52, 'Saba', 'sabasalamsaba@yahoo.com', '12341234@', NULL, '100009306259472', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (53, 'Salamon Bence', 'dsrbence@freemail.hu', 'qwertz1234', 'qwertz1234@', '100000730312822', 'DF36AB', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (54, 'Salwa', 'salwasamisalwa@yahoo.com', '12341234@', NULL, '100009178409020', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (55, 'Sanaa', 'sanaasamisanaa@yahoo.com', '12341234@', NULL, '100009490058186', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (56, 'Suha', 'suhasamisuha@yahoo.com', '12341234@', NULL, '100009432610339', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (57, 'Susa', 'susanbritton78@yahoo.com', '12341234@', NULL, '100009441129861', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (58, 'Samir Thaer', 'samirthaer@yahoo.com', 'castleage1234', NULL, '100006527910866', 'F78630', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (59, 'Setét', 'dsrsetet@freemail.hu', 'qwertz1234', 'qwertz1234@', '100003149177158', '3EDE71', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (60, 'Szabina Tóth', 'dsrszabina@freemail.hu', 'qwertz1234', 'qwertz1234@', '100004716961969', '2AAD42', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (61, 'Siberia', 'dsrsiberian@freemail.hu', 'qwertz1234', 'qwertz1234@', '100000846918017', '882C16', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (62, 'Stefan Knaub', 'dsrstefan@freemail.hu', 'qwertz1234', 'qwertz1234@', '100004722091010', '5A3BCC', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (63, 'Szabó Rózsa', 'dsrrozsa@freemail.hu', 'qwertz1234', 'qwertz1234@', '100001002417935', '658D2F', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (64, 'Szegedi Eszter', 'dsreszter@freemail.hu', 'qwertz1234', 'qwertz1234@', '100004740392338', '5E5EF4', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (65, 'Thaer Sadi', 'thaersadiowr@gmail.com', '&rose2&', NULL, '694519296', 'EE9D3B', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (66, 'Thair Sadi', 'red_thair@yahoo.com', 'castleage1234', NULL, '100001409155642', '6CF4AA', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (67, 'Thata Bata', 'thatabata1122@yahoo.com', 'castleage1234', NULL, '100004266458559', '9F06EC', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (68, 'Törpe', 'dsrtorpe@gmail.com', 'qwertz1234', 'qwertz1234', '100001560027538', '1CBC69', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (69, 'Udvari Beatrix', 'dsr.beatrix@gmail.com', 'qwertz1234@', NULL, '100000122726088', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (70, 'Varga Noémi', 'dsrnoemi@freemail.hu', 'qwertz1234', 'qwertz1234@', '100004991684460', '867C29', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (71, 'Végh Henriett', 'dsrhenriett@freemail.hu', 'qwertz1234', 'qwertz1234@', '100004706551309', 'A9D383', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (72, 'wafaa65aani@yahoo.com', 'wafaa65aani@yahoo.com', 'castleage1234', NULL, '100008267625966', NULL, NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (73, 'Zelovics György', 'dsrzelovicsgy@freemail.hu', 'qwertz1234@', 'qwertz1234@', '100000605753209', 'D37016', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (74, 'Zsuzsi Fekete', 'dsrzsuzsi@freemail.hu', 'qwertz1234', 'qwertz1234@', '100004705831768', 'A40D90', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (75, NULL, 'rosemarie92@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (76, NULL, 'dimitribelko85@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (77, NULL, 'serhaterdoga86@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (78, NULL, 'serhat-erdogmus1986@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (79, NULL, 'antonio.jose-reyes83@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (80, NULL, 'yalcinkilci1983@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (81, NULL, 'serapbastimur@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (82, NULL, 'fadimetasdelen@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (83, NULL, 'gracegundogan@gmx.de', 'DEL12345', 'null', 'null', 'null', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (85, 'jonskinner2@gmail.com', 'jonskinner2@gmail.com', 'Password1', NULL, '100001845082318', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (86, 'doraskinner2@gmail.com', 'doraskinner2@gmail.com', 'Password1', NULL, '100004614366842', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (87, 'arminmini3@freemail.hu', 'arminmini3@freemail.hu', 'Arminmini3', NULL, '1587372691', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (88, 'armin_m_w@yahoo.com ', 'armin_m_w@yahoo.com ', 'cck2014', NULL, '100000442628829', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (89, 'egon.alter99@gmail.com', 'egon.alter99@gmail.com', 'alterego99', NULL, '100002416596601', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (90, 'delgado7512@comcast.net', 'delgado7512@comcast.net', 'twinkle1', NULL, '1787448433', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (91, 'danut_m_r@yahoo.com', 'danut_m_r@yahoo.com', 'justforfriends', NULL, '', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (92, 'val_lau_h@yahoo.com', 'val_lau_h@yahoo.com', 'management', NULL, '100000472180204', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (93, 'a78dopes@yahoo.co.uk', 'a78dopes@yahoo.co.uk', 'dopema', NULL, '100001363961161', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (94, 'ktoodu@icloud.com', 'ktoodu@icloud.com', 'Kompok', NULL, '100005519610859', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (95, 'vera333@myway.com', 'vera333@myway.com', 'ouroboros', NULL, '129649470755522', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (96, 'hegesztelek@freemail.hu', 'hegesztelek@freemail.hu', '@Keletzsegeh', NULL, '120077345486545', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (97, 'DuFF10_73@hotmail.com', 'DuFF10_73@hotmail.com', 'g0gat0rs', NULL, '1037557496', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (98, 'dsr_mini@freemail.hu', 'dsr_mini@freemail.hu', 'Darkside01', NULL, '106382684069080', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (99, 'caminithree@freemail.hu', 'caminithree@freemail.hu', 'CAMini03', NULL, '100617074445814', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (100, 'caminisix@freemail.hu', 'caminisix@freemail.hu', 'CAMiniSix6', NULL, '102115268884850', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (101, 'nemzethyrahel@freemail.hu', 'nemzethyrahel@freemail.hu', 'CAMini04', NULL, '572629093418525', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (102, 'caminiseven@freemail.hu', 'caminiseven@freemail.hu', 'caminiseven01', NULL, '126155962558613', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (103, 'kerecsenjanos@freemail.hu', 'kerecsenjanos@freemail.hu', 'caminieight01', NULL, '113969290482946', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (104, 'camininina@freemail.hu', 'camininina@freemail.hu', 'CAmini09', NULL, '107748424489866', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (105, 'caminitena@freemail.hu', 'caminitena@freemail.hu', 'nqEi33vjY-_!dZ5', NULL, '107599208035531', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (106, 'eleven.ferenc@freemail.hu', 'eleven.ferenc@freemail.hu', 'CAMini11', NULL, '100698928779526', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (107, 'tothcsongor72@freemail.hu', 'tothcsongor72@freemail.hu', 'Qpwoei19', NULL, '102477832067253', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (108, 'kk19980808@freemail.hu', 'kk19980808@freemail.hu', 'fupa-vtQsF5UY9!', NULL, '104042338643662', '', NULL)");
            migrationBuilder.Sql("INSERT INTO Players (Id, DisplayName, Username, Password, EmailPassword, PlayerCode, ArmyCode, Cookie) VALUES (109, 'caminitwo@freemail.hu', 'caminitwo@freemail.hu', 'CAmini02', NULL, '111184279828735', '', NULL)");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
